// automatically generated by the FlatBuffers compiler, do not modify

package jp.oist.abcvlib.core.learning.fbclasses;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AudioTimestamp extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public AudioTimestamp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long framePosition() { return bb.getLong(bb_pos + 0); }
  public long nanotime() { return bb.getLong(bb_pos + 8); }

  public static int createAudioTimestamp(FlatBufferBuilder builder, long framePosition, long nanotime) {
    builder.prep(8, 16);
    builder.putLong(nanotime);
    builder.putLong(framePosition);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public AudioTimestamp get(int j) { return get(new AudioTimestamp(), j); }
    public AudioTimestamp get(AudioTimestamp obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

