// automatically generated by the FlatBuffers compiler, do not modify

package jp.oist.abcvlib.core.learning.fbclasses;

public final class CommAction {
  private CommAction() { }
  public static final byte Action0 = 0;
  public static final byte Action1 = 1;
  public static final byte Action2 = 2;

  public static final String[] names = { "Action0", "Action1", "Action2", };

  public static String name(int e) { return names[e]; }
}

