// automatically generated by the FlatBuffers compiler, do not modify

package jp.oist.abcvlib.core.learning.fbclasses;

public final class MotionAction {
  private MotionAction() { }
  public static final byte Stop = 0;
  public static final byte Forward = 1;
  public static final byte Backward = 2;
  public static final byte Left = 3;
  public static final byte Right = 4;

  public static final String[] names = { "Stop", "Forward", "Backward", "Left", "Right", };

  public static String name(int e) { return names[e]; }
}

