// automatically generated by the FlatBuffers compiler, do not modify

package jp.oist.abcvlib.core.learning.flatbuffers;

public final class motionAction {
  private motionAction() { }
  public static final byte standstill = 0;
  public static final byte forward = 1;
  public static final byte backward = 2;
  public static final byte turnfrontleft = 3;
  public static final byte turnfrontright = 4;
  public static final byte turnbackleft = 5;
  public static final byte turnbackright = 6;

  public static final String[] names = { "standstill", "forward", "backward", "turnfrontleft", "turnfrontright", "turnbackleft", "turnbackright", };

  public static String name(int e) { return names[e]; }
}

