name: Automated Releases

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  build-and-release:
    uses: oist/smartphone-robot-android/.github/workflows/build-check.yml@workflows

  release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/apps/basicSubscriber/build/outputs/apk/debug/basicSubscriber-debug.apk
            build/apps/basicSubscriber/build/outputs/apk/release/basicSubscriber-release-unsigned.apk
            build/apps/basicAssembler/build/outputs/apk/debug/basicAssembler-debug.apk
            build/apps/basicAssembler/build/outputs/apk/release/basicAssembler-release-unsigned.apk
            build/apps/backAndForth/build/outputs/apk/debug/backAndForth-debug.apk
            build/apps/backAndForth/build/outputs/apk/release/backAndForth-release-unsigned.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
