name: Automated Releases
on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  build-in-container:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Generate file paths
        id: generate_paths
        run: echo "paths=./.github/scripts/generate_output_paths.sh" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.generate_paths.outputs.paths }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
