name: Automated Releases
on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  build-in-container:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Generate file paths
        id: generate_paths
        run: |
          apps=$(jq -r '.apps | join(",")' apps-config.json)
          echo "debug_glob=./apps/{$apps}/build/outputs/apk/debug/{$apps}-debug.apk" >> $GITHUB_OUTPUT
          echo "release_glob=./apps/{$apps}/build/outputs/apk/release/{$apps}-release-unsigned.apk" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.generate_paths.outputs.debug_glob }}
            ${{ steps.generate_paths.outputs.release_glob }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
