name: Android CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: 'true'
    - name: Install Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git
        git --version
    - name: set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17.0'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.3.2
      with:
        gradle-version: 8.6
        cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
    - name: Build with Gradle
      run: ./gradlew build --configuration-cache
    - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v*.*.*')
        with:
          files: |
            ${{ github.workspace }}/apps/basicSubscriber/build/outputs/apk/debug/basicSubscriber-debug.apk
            ${{ github.workspace }}/apps/basicSubscriber/build/outputs/apk/release/basicSubscriber-release-unsigned.apk
            ${{ github.workspace }}/apps/basicAssembler/build/outputs/apk/debug/basicAssembler-debug.apk
            ${{ github.workspace }}/apps/basicAssembler/build/outputs/apk/release/basicAssembler-release-unsigned.apk
            ${{ github.workspace }}/apps/backAndForth/build/outputs/apk/debug/backAndForth-debug.apk
            ${{ github.workspace }}/apps/backAndForth/build/outputs/apk/release/backAndForth-release-unsigned.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
