name: Android CI

on:
  workflow_call:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: 'true'
    - name: Install Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git
        git --version
    - name: set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17.0'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.3.2
      with:
        gradle-version: 8.6
        cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
    - name: Build with Gradle
      run: ./gradlew build --configuration-cache
